//let age = 21;
//let message = age >= 18 ? "you are an adult": "you are a minor";
//console.log(message);
//let time = 24;
//let greeting = time < 12 ? "Good Morning": time < 18 ? "Good Afternoon": "Good Evening";
//console.log(greeting);
// let isStudent = false;
// let message = isStudent ? "You are a student": "You aren't a student";
// console.log(message);
let purchaseAmount = 142;
let discount = purchaseAmount >= 100 ? 10: 0;
console.log(`Your total is ${purchaseAmount - purchaseAmount * (discount / 100)}`);